
project_id = "jpbfprlpbiojfhshlhcp"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://preview--attiry-pendant-craft.lovable.app/"]
jwt_expiry = 3600
refresh_token_reuse_interval = 10
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[db]
port = 54322

[functions.products]
verify_jwt = true

[functions.orders]
verify_jwt = true

[functions.customers]
verify_jwt = true

[functions.analytics]
verify_jwt = true

[functions.inventory]
verify_jwt = true

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54325
